# Generated by Django 4.2.23 on 2025-08-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(default='do', max_length=100),
            preserve_default=False,
        ),
    ]
