# Generated by Django 4.2.23 on 2025-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('aadhar_id', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=10000)),
                ('status', models.CharField(default='open', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='help_request_images/')),
            ],
        ),
    ]
