# Generated by Django 4.2.23 on 2025-08-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0002_helprequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='helprequest',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='type',
            field=models.CharField(default='f', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='help_requests.bankdetails'),
        ),
    ]
