# Generated by Django 4.2.23 on 2025-08-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0003_bankdetails_helprequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='aadhar_id',
            field=models.IntegerField(),
        ),
    ]
