# Generated by Django 4.2.23 on 2025-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0004_alter_helprequest_aadhar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='aadhar_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
